config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  # get 'contact', to: 'publics#contact', as: 'contact'

  resources :products do
    member do
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end
  resources :favorites do
    collection do
      get :wishlist
    end
  end
  resources :confirmations, only: [:new, :create]
  resources :subscribes
  resources :landing_pages
  resources :comments
  resources :inquiries
  resources :orders do
    collection do
      get :checkout
    end
    member do
      get :review
    end
  end
  resources :guest_books
  resources :order_items, only: [:create, :update, :destroy]
  resources :users do
    member do
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end
  resources :xhrs do
    collection do
      get :cities
      get :shipment_provinces
      get :shipment_cities
      get :shipment_states
      get :shipping_price
    end
  end

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :categories do
      collection do
        post :do_multiple_act
      end
    end
    resources :brands do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
      end
    end
    resources :orders do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_items
    resources :confirmations do
      collection do
        post :do_multiple_act
      end
    end
    resources :shipments do
      collection do
        post :do_multiple_act
        post :import
      end
    end
    resources :regions do
      collection do
        post :do_multiple_act
      end
    end
    resources :comments do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :subscribes do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members, only: [:edit, :update, :show]
    resources :merchants, only: [:edit, :update, :show]
    resources :products
    resources :favorites
    resources :orders
    resources :order_items
    resources :inquiries
  end

  # mount Ckeditor::Engine => '/ckeditor'
  # post '/rate' => 'rater#create', :as => 'rate'

  # get '/backend',                   to: 'backend#home',                     as: 'backend_home'
  # get '/member',                    to: 'member#home',                      as: 'member_home'
  # get '/profile',                   to: 'member#profile',                   as: 'profile'
  # get 'search',                     to: 'publics#search',                   as: 'search'
  # get 'portfolio/:id',              to: 'publics#portfolio',                as: 'portfolio'
  # get "like/:id",                   to: "publics#upvote",                   as: 'like'
  # get "document_download/:id",      to: "publics#document_download",        as: 'document_download'
  # get "landing_page/:id",           to: "publics#landing_page",             as: 'landing_page'
  # get "catalog_category_child",     to: "catalogs#catalog_category_child",  as: 'catalog_category_child'
  # get "review/:id",                 to: "orders#review",                    as: 'review'

  # resources :catalogs do
  #   member do
  #     get 'comments'
  #     get 'support'
  #     get 'ticket'
  #     put "like",     to: "catalogs#upvote"
  #     match :upvote, path: 'like', via: [:get, :post, :put]
  #   end
  # end

  # resource :orders do
  #   collection do
  #     get :paid
  #     get :revoked
  #     post :ipn
  #   end
  # end

  # resources :order_items, only: [:create, :update, :destroy]
  # resources :comments
  # resources :tickets
  # resources :subscribes
end

app/views/shareds/_already_order.html.slim
button class="btn btn-info btn-lg full-width"
  | You have already order this item

app/views/shareds/_carousel.html.slim
section.section-carousel
  .container
    .col-md-9
      #transition-timer-carousel class="home-carousel carousel slide transition-timer-carousel" data-ride="carousel"
        .carousel-inner
          - @setting.galleries.each_with_index do |resource, index|
            div class=['item', "#{'active' if index == 0}"]
              .main-text
                .text-center
                  h1 Shop directly from people around the world
                  p Buy from creative people who care about quality and craftsmanship
                  = link_to products_path do
                    button class="btn btn-alert btn-create-sell"
                      | START SHOP
              = image_tag resource.file.url(:large)
        a class="left carousel-control" href="#transition-timer-carousel" data-slide="prev"
          span.glyphicon.glyphicon-chevron-left
        a class="right carousel-control" href="#transition-timer-carousel" data-slide="next"
          span.glyphicon.glyphicon-chevron-right
        hr class="transition-timer-carousel-progress-bar animate"

    .col-md-3.mock-side-right
      .mock-right1
        = image_tag 'mock_right1.jpg'
      .mock-right2
        .overlay
        = image_tag 'mock_right2.jpg'

app/views/shareds/_cart_text.html.slim
= link_to orders_path do
  strong
    span.fa.fa-shopping-cart
    | SHOPPING CART
  br
  span #{current_order.order_items.size} Items

app/views/shareds/_chat.html.slim
- user = @product.try(:user) || @user
- profile = user.try(:profile)
.panel.panel-default.chat-window
  .panel-heading
    h3 class="panel-title"
      = @user.try(:merchant_info).try(:title).titleize
      span class="glyphicon glyphicon-remove"
      span class="glyphicon glyphicon-minus"
  .panel-body
    .break
    .row
      .col-xs-4
        = link_to image_tag(profile.avatar.url(:small)), user_path(user), class: "pull-left ava-list"
      .col-xs-8
        b
          = user.try(:username)
        .useridUser Id: #{user.try(:code)}
      .col-xs-12
        .wellcome
          p 'Hi, saya lihat bahwa anda sedang melihat listing saya, ada yang bisa saya bantu?'
      .col-xs-12
        .wellcome
          p class="last-name"
          p class="last-message"
  .panel-form
    = form_for Inquiry.new, url: create_instant_message_inquiries_path, method: 'post', html: {class: 'form-sms-instant-message'} do |f|
      - if @product.present?
        = f.hidden_field :inquiriable_id, value: @product.id
        = f.hidden_field :inquiriable_type, value: @product.class
        = f.hidden_field :owner_id, value: @product.try(:user).try(:id)
      - else
        = f.hidden_field :owner_id, value: @user.try(:id)
      - unless current_user.present?
        / = f.text_field :name, class: 'form-name', required: true, placeholder: 'name ...'
        / = f.text_field :phone, class: 'form-phone', required: true, placeholder: 'phone ...'
        = f.email_field :email, class: 'form-email', required: true, placeholder: 'email ...'
      - else
        = f.hidden_field :name, class: 'form-name', value: current_user.username
      = f.text_field :message, class: "form-chat", placeholder: 'messages ...', required: true
      button class="btn btn-chat" type="submitSend" Send

app/views/shareds/_footer.html.slim
.col-xs-12
  .container
    - if params[:controller] == 'publics' && params[:action] == 'home' || params[:controller] == 'products'
      .col-md-9
        .newsletter
          = form_for Subscribe.new, url: subscribes_path, method: 'post', html: {class: 'form_newsletter'} do |subscribe|
            .description
              h5.heading Get a Newsletter
              p We will respond within 3 bussiness days
            .input-group
              = subscribe.text_field :email, class: 'form-control', placeholder: 'Your Email Address'
              .input-group-btn
                button class="btn by-search" type="submit"
                  i class="fa fa-envelope"
        .hotline
          = image_tag 'hotline.png', class: 'img-responsive'
      
      .col-md-3
        .mini-map#maps

      .col-md-12
        .info-account-bank
          = image_tag 'mandiri.png'
          = image_tag 'bca.png'
          = image_tag 'bni.png'
          = image_tag 'bri.png'
    
footer.footer
  .container
    .col-md-3
      h3 About Us
      p #{@setting.description}
    .col-md-3
      h3 Buy
      ul.footer-box-list
        - @landing_pages.buy.each do |page|
          li
            = link_to page.title, landing_page_path(page)
    .col-md-3
      h3 Sell
      ul.footer-box-list
        - @landing_pages.sell.each do |page|
          li
            = link_to page.title, landing_page_path(page)
    .col-md-3
      h3 Help
      ul.footer-box-list
        - @landing_pages.help.each do |page|
          li
            = link_to page.title, landing_page_path(page)

  .copyright
    .container
      .col-md-6.col-sm-12.col-xs-12
        p
          = @setting.footer_tags
      .col-md-6.col-sm-12.col-xs-12
        .follow-us
          b
            | Find Us On &nbsp;&nbsp;
          a href="#{@setting.facebook}" class="btn site-facebook"
            i class="fa fa-facebook"
          a href="#{@setting.twitter}" class="btn site-twitter"
            i class="fa fa-twitter"

= render 'shareds/sign_in'

app/views/shareds/_form_contact.html.slim
.modal.fade.modal-contact id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
  .modal-dialog.modal-sm
    .modal-content.modal-content-message
      .modal-header.modal-header-info
        h3 align="center" Box Message
      .modal-body.modal-sign.modal-contact-form
        = form_for Inquiry.new, url: inquiries_path, method: 'post' do |f|
          - if @product.present?
            = f.hidden_field :inquiriable_id, value: @product.id
            = f.hidden_field :inquiriable_type, value: @product.class
            = f.hidden_field :owner_id, value: @product.try(:user).try(:id)
          - else
            = f.hidden_field :owner_id, value: @user.try(:id)
          fieldset
            div style="#{'display:none' if current_user.present?}"
              .form-group
                label class="control-label" Name:
                .controls
                  = f.text_field :name, class: "form-control", required: true, placeholder: 'ex. alam topani ...', value: "#{current_user.try(:profile).try(:full_name)}"
              .form-group
                label class="control-label" Phone:
                .controls
                  = f.text_field :phone, class: "form-control", required: true, placeholder: 'ex. +6285.2345 ...', value: "#{current_user.try(:contact).try(:phone)}"
              .form-group
                label class="control-label" Email:
                .controls
                  = f.email_field :email, class: "form-control", required: true, placeholder: 'ex. alam@example.com ...', value: "#{current_user.try(:email)}"
            .form-group
              label class="control-label" Message:
              .controls
                = f.text_area :message, class: "form-control", required: true 
            .form-group
              .controls
                = f.submit 'Send Now', class: "btn btn-primary btn-block btn-success"

app/views/shareds/_gmap_js.html.erb
<script type="text/javascript">
  $('#maps').gmap3({
    map:{
      options:{
        center:[<%= @setting.longitude %>, <%= @setting.latitude %>],
        zoom: 15,
        scrollwheel: false
      }
    },
    marker:{
      values:[
      {latLng:[<%= @setting.longitude %>, <%= @setting.latitude %>], data:"<b><%= @setting.title %></b><br><%= @setting.address %>"},
      ],
      options:{
        draggable: false
      },
      events:{
        mouseover: function(marker, event, context){
          var map = $(this).gmap3("get"),
          infowindow = $(this).gmap3({get:{name:"infowindow"}});
          if (infowindow){
            infowindow.open(map, marker);
            infowindow.setContent(context.data);
          } else {
            $(this).gmap3({
              infowindow:{
                anchor:marker,
                options:{content: context.data}
              }
            });
          }
        },
        mouseout: function(){
          var infowindow = $(this).gmap3({get:{name:"infowindow"}});
          if (infowindow){
            infowindow.close();
          }
        }
      }
    }
  });
</script>

app/views/shareds/_invoice.html.slim
.panel.panel-default
  .panel-heading
    h4.text-center.uppercase
      | Invoice <strong>#{@order.code}</strong>
    center.small
      | <b>Invoice Date : </b> 
      = @order.try(:purchased_at).strftime("%B, %d, %Y") if @order.purchased_at
      br
      | <b>Due Date : </b> 
      = (@order.try(:purchased_at)+ 3.days).strftime("%B, %d, %Y") if @order.purchased_at
      br
      - if @order.shipping_number.present?
        | <b>Shipping Number : </b> 
        = @order.try(:shipping_number)
      - if current_user.admin?
        = form_for @order, url: backend_order_path(@order), method: 'put', html: {class: ''} do |f|
          = f.select :order_status_id, options_for_select(PaymentStatus.to_a, @order.order_status_id), {prompt: 'Select Status'}
          = f.submit :change, class: 'btn btn-xs btn-info'
  .panel-body
    .row
      .col-md-12
        h5.uppercase
          | Invoiced To
        = @order.try(:payer_company)
        br
        = @order.try(:payer_name)
        br
        small
          | Shipping: &nbsp;
          = @order.address.place_info
          - if current_user.admin?
            = form_for @order, url: backend_order_path(@order), method: 'put', html: {class: ''} do |f|
              = f.text_field :shipping_number, class: '', placeholder: 'Shipping Number'
              br
              = f.select :track_order, options_for_select(TrackOrder.to_a, @order.track_order), {prompt: 'Status Track Order'}
              br
              = f.submit :change, class: 'btn btn-xs btn-info'
    .break
    .break
    .shopping-cart
      .row
        .col-md-12
          .catalog-item-show
            .table-responsive.table-order-list
              table class="table table-striped"
                thead
                  tr
                    td width="40%"
                      | <strong>Item Name</strong>
                    td class="text-center"
                      | <strong>Quantity</strong>
                    td class="text-center"
                      | <strong>Weight</strong>
                    td class="text-right"
                      | <strong>Item Price</strong>
                tbody
                  - @order.order_items.each do |order_item| 
                    tr
                      td
                        .avatar-author
                          = image_tag order_item.try(:product).try(:galleries).try(:first).try(:file).url(:medium)
                        small.uppercase
                          | Id #{@order.code} <br>
                        = link_to "#{order_item.product.title}", product_path(order_item.product.slug), class: 'title-product'
                        / - if current_user.admin?
                        /   = form_for order_item, url: backend_order_item_path(order_item), method: 'put', html: {class: ''} do |f|
                        /     = f.select :track_order, options_for_select(TrackOrder.to_a, order_item.track_order), {prompt: 'Status Track Order'}
                        /     = f.submit :change, class: 'btn btn-xs btn-info'
                      td.text-center
                        span
                          = order_item.quantity
                      td.text-center
                        span
                          | #{order_item.weight.to_i} gram
                      td.text-right
                        span
                          = get_currency(order_item.total_price)
                  tr
                    td class="highrow"
                    td class="highrow"
                    td class="highrow text-center"
                      | <h5>Total Price Shopping</h5>
                    td class="highrow text-right"
                      | <h5>#{get_currency(@order.total)}</h5>
                  tr
                    td class="highrow"
                    td class="highrow"
                    td class="highrow text-center"
                      | <h5>Shipping #{@order.shipping_method}</h5>
                    td class="highrow text-right"
                      | <h5>#{get_currency(@order.shipping_price) if @order.shipping_price.present?}/ #{@order.total_weight?} gram</h5>
                  tr
                    td class="highrow"
                    td class="highrow"
                    td class="highrow text-center"
                      | <h5>TOTAL</h5>
                    td class="highrow text-right"
                      | <h5>#{get_currency(@order.total_price?)}</h5>

            h4 Transaction
            .table-responsive.table-order-list
              table class="table table-striped"
                thead
                  tr
                    td class="text-center" width="20%"
                      | <strong>Transaction Date</strong>
                    td class="text-center" width="20%"
                      | <strong>Payer</strong>
                    td class="text-center"
                      | <strong>Payment To</strong>
                    td class="text-center"
                      | <strong>Payment Status</strong>
                    td class="text-center"
                      | <strong>Transaction ID</strong>
                tbody
                  tr
                    td.text-center
                      span
                        = @order.try(:purchased_at).strftime("%B, %d, %Y") if @order.purchased_at
                    td.text-center
                      span
                        = @order.try(:payer_name)
                    td.text-center
                      span
                        = @order.try(:paymentTo)
                    td.text-center
                      span
                        = @order.status?
                    td.text-center
                      span
                        = @order.try(:payment_token)

            h4 Shipping
            .table-responsive.table-order-list
              table class="table table-striped"
                thead
                  tr
                    td class="text-center" width="15%"
                      | <strong>Receiver</strong>
                    td class="text-center" width="20%"
                      | <strong>Shipping Method</strong>
                    td class="text-center" width="15%"
                      | <strong>Shipping Order</strong>
                    - if @order.shipping_number.present?
                      td class="text-center" width="15%"
                        | <strong>Shipping Number</strong>
                    td class="text-center" width="10%"
                      | <strong>Phone</strong>
                    td class="text-center"
                      | <strong>Shipping Address</strong>
                tbody
                  tr
                    td.text-center
                      span
                        = @order.try(:payer_name)
                    td.text-center
                      span
                        = @order.try(:shipping_method)
                    td.text-center
                      span
                        = @order.try(:track_order)
                    - if @order.shipping_number.present?
                      td.text-center
                        span
                          = @order.try(:shipping_number)
                    td.text-center
                      span
                        = @order.try(:payer_phone)
                    td.text-center
                      span
                        = @order.address.place_info

app/views/shareds/_list_message.html.slim
li
  .header-inbox-pop
    small.pull-left
      | Messages(#{@latest_inquiries.size})
    = link_to '<small class="pull-right">View Inbox</small>'.html_safe, userpage_inquiries_path
  .box-inbox-pop
    = '<span class="p-message">No data founds!</span>'.html_safe unless @latest_inquiries.present?
    - @latest_inquiries.limit(5).each do |i|
      - if i.parent.present?
        = link_to userpage_inquiry_path(i.parent.id) do
          .list-message-limit
            | <div class='usr'><b>#{i.user.username}</b></div>
            | <div>#{i.message}</div>
      - elsif i.parent.blank?
        = link_to userpage_inquiry_path(i) do
          .list-message-limit
            | <div class='usr'><b>#{i.name}</b></div>
            | <div>#{i.message}</div>

app/views/shareds/_setting.html.slim
= favicon_link_tag "#{@setting.favicon.url(:thumb)}"
meta http-equiv="X-UA-Compatible" content="IE=edge"
meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"

- if params[:controller] == 'products' && params[:action] == 'show'
  - @title = "#{@product.title}"
  - @url = "#{product_url(@product)}"
  title
    = @title
  meta name="author" content="#{@product.user.username rescue nil}"
  meta name='keywords' content="#{@product.title}, #{@product.category.name}"
  meta name="description" content="#{strip_tags(@product.description)}"
  meta property="og:title" content="#{@title}"
  meta property="og:type" content="website"
  meta property="og:site_name" content="#{@url}"
  meta property="og:url" content="#{@url}"
  meta property="og:image" content="#{image_url @product.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium) rescue nil }"
  meta property="og:description" content="#{@title}"
  meta property="article:publisher" content="#{@setting.facebook}"
  meta name="twitter:card" content="summary"
  meta name="twitter:url" content="#{@url}"
  meta name="twitter:title" content="#{@title}"
  meta name="twitter:description" content="#{strip_tags(@product.description)}"
  meta name="twitter:creator" content="#{@product.user.username rescue nil}"
  meta name="twitter:image:src" content="#{image_url @product.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium) rescue nil }"
- else
  title
    = @setting.title
  meta content="#{@setting.author}" name='author'
  meta content="#{@setting.keywords}" name='keywords'
  meta content="#{strip_tags(@setting.description)}" name="description"

meta content="#{@setting.robot}" name='robots'
meta content="#{@setting.corpyright}" name='copyright'
meta content="#{@setting.revisit}" name='revisit'
meta content="#{@setting.expires}" name='expires'
meta content="#{@setting.revisit_after}" name='revisit-after'
meta content="#{@setting.geo_placename}" name='geo.placename'
meta content="#{@setting.language}" name='language'
meta content="#{@setting.country}" name='geo.country'
meta content="#{@setting.content_language}" http-equiv='Content-Language'
meta content="#{@setting.distribution}" name='distribution'
meta content="#{@setting.generator}" name='generator'
meta content="#{@setting.rating}" name='rating'
meta content="#{@setting.target}" name='target'
meta content='true' name='MSSmartTagsPreventParsing'
meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
meta content='index, follow' name='googlebot'
meta content='follow, all' name='Googlebot-Image'
meta content='follow, all' name='msnbot'
meta content='follow, all' name='Slurp'
meta content='follow, all' name='ZyBorg'
meta content='follow, all' name='Scooter'
meta content='all' name='spiders'
meta content='all' name='WEBCRAWLERS'
meta content='noodp' name='robots'
meta content='noydir' name='robots'
meta content="#{@setting.robot}" name='search engines'

app/views/shareds/_top_menu.html.slim
.top-bar
  .container
    .col-md-6.col-sm-12.col-xs-12
      ul.top_info
        li
          = link_to "<i class='fa fa-phone'></i> #{@setting.contact}".html_safe, root_path
        li
          = link_to '<i class="fa fa-envelope-o"></i> Contact Us'.html_safe, guest_books_path
        li
          = link_to '<i class="fa fa-money"></i> Payment Confirmation'.html_safe, new_confirmation_path
    .col-md-6.col-sm-12.col-xs-12
      ul.nav-account
        - unless current_user
          li
            = link_to '<i class="fa fa-edit" aria-hidden="true"></i>Register'.html_safe, new_user_registration_path
          li
            a href="#signin" data-toggle="modal" data-target=".bs-modal-sm" <i class="fa fa-key" aria-hidden="true"></i> Sign In
        - else
          li
            = link_to '<i class="fa fa-mail-reply" aria-hidden="true"></i> Sign Out'.html_safe, destroy_user_session_path, method: 'delete'
          li
            a.dropdown-toggle data-toggle="dropdown"
              i.fa.fa-user
              = current_user.email
              i.fa.fa-caret-down
            ul.dropdown-menu
              li
                = link_to 'Beranda <i class="fa fa-home pull-right"></i>'.html_safe, userpage_dashboard_path
              li
                = link_to 'Whishlists <i class="fa fa-heart-o pull-right"></i>'.html_safe, userpage_favorites_path
              li
                = link_to 'My Orders <i class="fa fa-files-o pull-right"></i>'.html_safe, userpage_orders_path
              li
                = link_to 'Settings <i class="fa fa-wrench pull-right"></i>'.html_safe, user_edit_url(current_user.type, current_user)
              li
                = link_to 'Sign Out <i class="fa fa-mail-reply pull-right"></i>'.html_safe, destroy_user_session_path, method: 'delete'

.top-brand-web
  .container
    .col-md-3
      = link_to "<h1>#{image_tag @setting.logo.url(:small)}</h1>".html_safe, root_path, class: "brand"
    .col-md-6
      = form_for :search, url: products_path(params), method: 'get' do
        = hidden_field_tag :category, params[:category] if params[:category].present?
        .input-group
          = text_field_tag :key, params[:key], class: 'form-control', placeholder: 'Search by keywords ...'
          .input-group-btn
            button class="btn by-search" type="submit"
              i class="fa fa-search"
    .col-md-3
      - if current_user.present?
        .cart-text.btn.cart-btn
          = render 'shareds/cart_text'
      - else
        .cart-text.btn.cart-btn
          = link_to '#' do
            strong
              span.fa.fa-shopping-cart
              | SHOPPING CART
            br
            span 0 Items

#top-navigation
  nav.navbar-default
    .container
      .col-md-12
        .navbar-header
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs"
            span class="sr-only">Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
        .collapse.navbar-collapse id="bs-megadropdown-tabs"
          ul.nav.navbar-nav.top-menu
            li
              = link_to "All", products_path
            - @categories.each do |category|
              li.dropdown
                a data-toggle="dropdown" href="#" class="dropdown-toggle"
                  = category.name
                  i.fa.fa-caret-down
                ul.dropdown-menu.list-dropdown-menu
                  - category.children.latest.each do |child|
                    li
                      = link_to "<span>#{child.name}</span> <span class='pull-right bold'>#{child.products.size}</span>".html_safe, products_path(params.merge(category: child.name)), method: 'get'